# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu

# friends link
links:
  - name: インターネット蟹工船
    url: https://nere9.help

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/satoshicano
- slug: twitter
  url: https://twitter.com/satoshicano
- slug: rss
  url: /atom.xml

google_analytics: UA-78915534-3